### ISSUE TITLE
Question regarding the contained `resources`

### ISSUE THREAD

**Issue by kyoungrok0517** [tttthomasssss/sense2017#1]
Hi, I'm planning to use your dataset for my new model, but having trouble interpreting the organization of the contained `resources` data. Take `2_senses/collins` for example, the header is composed of 4 tab-separated columns: `Lexeme\tSense Definition 1\tSense Definition 2\tPoS`, but the data rows are composed of 5 columns (contains 3 sense defs, not 2 as expected). How is that? Am I getting something wrong?

**Comment by kyoungrok0517** [comment]
```
Lexeme	Sense Definition 1	Sense Definition 2	PoS
lost	If something is lost, or gets lost, you cannot find it, for example because you have forgotten where you put it.	If something is lost, or gets lost, you cannot find it, for example because you have forgotten where you put it.	If you describe something as lost, you mean that you no longer have it or it no longer exists.	Adjective
true	If you use true to describe something or someone, you approve of them because they have all the characteristics or qualities that such a person or thing typically has.	If you use true to describe something or someone, you approve of them because they have all the characteristics or qualities that such a person or thing typically has.	If you are true to someone, you remain committed and loyal to them. If you are true to an idea or promise, you remain committed to it and continue to act according to it.	Adjective
...
```

**Comment by tttthomasssss** [comment]
Hi, the data in the repository are just the definitions, but not the example sentences - I have sent you an email with the necessary details!

**Comment by kyoungrok0517** [comment]
Wow... thanks for the fast response! Hope to see you in other conferences! (I in fact watched you presenting the paper at EACL 2017)
